#!/bin/bash
loop_body="${@:1:1}"
new_script='while ($_ = $*IN.get).defined { '$loop_body' }'
if (perl6 -c -e "$new_script" > /dev/null 2>&1); then
    cat "${@:2}" | perl6 -e "$new_script"
else
    perl6 -c -e "$new_script"
fi
